title: Coffee Shop Sales Analysis
logo: #path to picture 
show_download: false
remote_theme: pages-themes/minimal@v0.2.0
toc: true
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Link custom styles
include: ["assets/css/style.css"]
